### ISSUE TITLE
개발 환경 설정

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/simmons_transcendence#4]
- [x] webstorm 자리 옮겨 다녀도 바로 쓸 수 있게 셋업 @nfl1ryxditimo12 
- [ ] 동일 버전으로 셋업 @gilee
- [ ] 셋업된 환경으로 간단한 crud 돌려보기 @mtak0235 @taeskim-42

**Comment by nfl1ryxditimo12** [comment]
[자리옮길 때 마다 노드 깔기 귀찮다면 여기 클릭](https://github.com/mtak0235/simmons_transcendence/wiki/%EC%9E%90%EB%A6%AC%EC%98%AE%EA%B8%B8-%EB%95%8C-%EB%A7%88%EB%8B%A4-%EB%85%B8%EB%93%9C%EA%B9%94%EA%B8%B0-%EA%B7%80%EC%B0%AE%EB%8B%A4!!)
