### ISSUE TITLE
User Status 세분화

### ISSUE THREAD

**Issue by nfl1ryxditimo12** [mtak0235/simmons_transcendence#54]
## 이유
- 현재 `inGame`, `online`, `offline` 3가지로 사용자 상태를 관리하는 중임
- 이러한 경우 유저가 `outChannel` 이벤트를 요청했을 때 channel 객체에서 유저가 속해있을 것 같은 배열을 모두 변경 해줘야 함
- 필요할 법한 배열을 모두 변경하면 효율적이지 못해 유저 status를 세분화 하여 속해있는 위치를 특정하기 위함
- 유저가 속한 위치를 특정할 경우 배열 순회를 적게 가져갈 수 있음으로 효율적이라는 판단이 됨

## 기존 STATUS

```js
export const STATUS_LAYER = {
  inGame: 'inGame',
  online: 'online',
  offline: 'offline',
} as const;
```

## 변경될 STATUS

```js
export const STATUS_LAYER = {
  inGame: 'inGame',
  waitingGame: 'waitingGame',
  watchingGame: 'watchingGame',
  online: 'online',
  offline: 'offline',
} as const;
```

## 클라이언트에 응답되는 status

- 기존과 동일하게 channel에 접속되어 있다면 `inGame` 으로 응답 될 것임
- `waitingGame`, `watchingGame` status는 서버 flag 용도로만 사용 될 것임

**Comment by mtak0235** [comment]
status에 접근하는  부분 모두 수정이 필요하겠군요 상태관리만 잘 한다면 말씀하신부분처럼 배열 순회가 더 줄어들 것 같습니다!
